version: "3.9"
services:
  db:
    image: postgres:14.8-alpine
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
    ports:
      - 5432:5432
    restart: always

  api:
    build:
      context: .
    volumes:
      - ./src/:/src/
      - ./prod_records/:/tmp/storage/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./src/.env
    command: >
      python3 server.py